/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutAccountModal: typeof import('./src/components/profile/AboutAccountModal.vue')['default']
    AccountSettings: typeof import('./src/components/settings/AccountSettings.vue')['default']
    Activity: typeof import('./src/components/profile/Activity.vue')['default']
    AdditionalInfoPost: typeof import('./src/components/AdditionalInfoPost.vue')['default']
    CommentMenu: typeof import('./src/components/CommentMenu.vue')['default']
    ConfirmationModal: typeof import('./src/components/ConfirmationModal.vue')['default']
    ContentSettings: typeof import('./src/components/settings/ContentSettings.vue')['default']
    DatePickerInput: typeof import('./src/components/DatePickerInput.vue')['default']
    FacebookLoginButton: typeof import('./src/components/FacebookLoginButton.vue')['default']
    Filter: typeof import('./src/components/feed/Filter.vue')['default']
    FormAutocomplete: typeof import('./src/components/FormAutocomplete.vue')['default']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    FormTextarea: typeof import('./src/components/FormTextarea.vue')['default']
    GoogleLoginButton: typeof import('./src/components/GoogleLoginButton.vue')['default']
    HelpSettings: typeof import('./src/components/settings/HelpSettings.vue')['default']
    MentionPopover: typeof import('./src/components/MentionPopover.vue')['default']
    MentionTextarea: typeof import('./src/components/MentionTextarea.vue')['default']
    MobileSlide: typeof import('./src/components/MobileSlide.vue')['default']
    MoblileNavbar: typeof import('./src/components/MoblileNavbar.vue')['default']
    NotificationSettings: typeof import('./src/components/settings/NotificationSettings.vue')['default']
    PopularTags: typeof import('./src/components/sidebars/PopularTags.vue')['default']
    PostCard: typeof import('./src/components/feed/PostCard.vue')['default']
    PostMenu: typeof import('./src/components/feed/PostMenu.vue')['default']
    PremiumSettings: typeof import('./src/components/settings/PremiumSettings.vue')['default']
    PrivacyPosting: typeof import('./src/components/PrivacyPosting.vue')['default']
    PrivacySettings: typeof import('./src/components/settings/PrivacySettings.vue')['default']
    ProfileCard: typeof import('./src/components/sidebars/ProfileCard.vue')['default']
    Rightbar: typeof import('./src/components/sidebars/Rightbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecuritySettings: typeof import('./src/components/settings/SecuritySettings.vue')['default']
    Sidebar: typeof import('./src/components/sidebars/Sidebar.vue')['default']
    StepFive: typeof import('./src/components/create-post/step-five.vue')['default']
    StepFour: typeof import('./src/components/create-post/step-four.vue')['default']
    StepOne: typeof import('./src/components/create-post/step-one.vue')['default']
    StepThree: typeof import('./src/components/create-post/step-three.vue')['default']
    StepTwo: typeof import('./src/components/create-post/step-two.vue')['default']
    UploadFile: typeof import('./src/components/UploadFile.vue')['default']
    UserCard: typeof import('./src/components/profile/UserCard.vue')['default']
    WhoToFollow: typeof import('./src/components/sidebars/WhoToFollow.vue')['default']
  }
}
