/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/check-inbox': RouteRecordInfo<'/check-inbox', '/check-inbox', Record<never, never>, Record<never, never>>,
    '/congrats': RouteRecordInfo<'/congrats', '/congrats', Record<never, never>, Record<never, never>>,
    '/create-post': RouteRecordInfo<'/create-post', '/create-post', Record<never, never>, Record<never, never>>,
    '/explore': RouteRecordInfo<'/explore', '/explore', Record<never, never>, Record<never, never>>,
    '/failure-age': RouteRecordInfo<'/failure-age', '/failure-age', Record<never, never>, Record<never, never>>,
    '/failure-resume': RouteRecordInfo<'/failure-resume', '/failure-resume', Record<never, never>, Record<never, never>>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/library': RouteRecordInfo<'/library', '/library', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/notifications': RouteRecordInfo<'/notifications', '/notifications', Record<never, never>, Record<never, never>>,
    '/otp': RouteRecordInfo<'/otp', '/otp', Record<never, never>, Record<never, never>>,
    '/post/[id]': RouteRecordInfo<'/post/[id]', '/post/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/post-success-created': RouteRecordInfo<'/post-success-created', '/post-success-created', Record<never, never>, Record<never, never>>,
    '/premium': RouteRecordInfo<'/premium', '/premium', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/set-password': RouteRecordInfo<'/set-password', '/set-password', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/verify-email-change': RouteRecordInfo<'/verify-email-change', '/verify-email-change', Record<never, never>, Record<never, never>>,
    '/verify-new-user': RouteRecordInfo<'/verify-new-user', '/verify-new-user', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/404.vue': {
      routes: '/404'
      views: never
    }
    'src/pages/check-inbox.vue': {
      routes: '/check-inbox'
      views: never
    }
    'src/pages/congrats.vue': {
      routes: '/congrats'
      views: never
    }
    'src/pages/create-post.vue': {
      routes: '/create-post'
      views: never
    }
    'src/pages/explore.vue': {
      routes: '/explore'
      views: never
    }
    'src/pages/failure-age.vue': {
      routes: '/failure-age'
      views: never
    }
    'src/pages/failure-resume.vue': {
      routes: '/failure-resume'
      views: never
    }
    'src/pages/forgot-password.vue': {
      routes: '/forgot-password'
      views: never
    }
    'src/pages/library.vue': {
      routes: '/library'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/notifications.vue': {
      routes: '/notifications'
      views: never
    }
    'src/pages/otp.vue': {
      routes: '/otp'
      views: never
    }
    'src/pages/post/[id].vue': {
      routes: '/post/[id]'
      views: never
    }
    'src/pages/post-success-created.vue': {
      routes: '/post-success-created'
      views: never
    }
    'src/pages/premium.vue': {
      routes: '/premium'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/set-password.vue': {
      routes: '/set-password'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/verify-email-change.vue': {
      routes: '/verify-email-change'
      views: never
    }
    'src/pages/verify-new-user.vue': {
      routes: '/verify-new-user'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
